# Generated by Django 4.1.3 on 2022-11-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_patient_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="signature",),
        migrations.AddField(
            model_name="patient",
            name="medcare",
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visits",
            name="disbursement_date",
            field=models.DateField(default="2020-01-01", null=True),
        ),
    ]
