# Generated by Django 4.1.3 on 2022-11-11 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_visits_visit_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="assigned_to",),
        migrations.AddField(
            model_name="patient",
            name="assigned_to",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
