# Generated by Django 4.1.3 on 2022-11-11 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_patient_assigned_to_visits_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="visits",
            name="visit_time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
