# Generated by Django 4.1.3 on 2022-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_report_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="visit",),
        migrations.AddField(
            model_name="report",
            name="blood_type",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                default="NULL",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="city",
            field=models.CharField(default="NULL", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="first_name",
            field=models.CharField(default="No Name", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="last_name",
            field=models.CharField(default="No Name", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="medcare",
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="pincode",
            field=models.CharField(default=True, max_length=20, null=True),
        ),
    ]
