# Generated by Django 4.0.5 on 2022-07-13 21:42

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('user_roles', models.CharField(choices=[('OfficeAdmin', 'OfficeAdmin'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=20)),
                ('date_of_birth', models.DateField(default='2000-01-01', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=50, null=True)),
                ('county', models.CharField(max_length=50, null=True)),
                ('subcounty', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=150, null=True)),
                ('mobile', models.CharField(default='0', max_length=10, null=True)),
                ('pincode', models.CharField(default='', max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'permissions': (('OfficeAdmin', 'Can manage all users accounts.'), ('Add_user', 'Can add user accounts.'), ('edit_patients', 'Can edit patient accounts.'), ('view_patients', 'Can view patient accounts.'), ('manage_patients', 'Can manage patient accounts.')),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('national_id', models.PositiveIntegerField(default=0, unique=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5)),
                ('occupation', models.CharField(max_length=200)),
                ('annual_income', models.BigIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('subcounty', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=150)),
                ('mobile', models.CharField(default=True, max_length=20, null=True)),
                ('pincode', models.CharField(default=True, max_length=20, null=True)),
                ('photo', models.ImageField(null=True, upload_to='static/img/users')),
                ('signature', models.ImageField(null=True, upload_to='static/img/signatures')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Served', 'Served'), ('Inservice', 'Inservice'), ('Waiting', 'Waiting')], default='UnAssigned', max_length=50, null=True)),
                ('bookfee_amount', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(max_length=50, unique=True)),
                ('visit_date', models.DateField(default='2020-01-01', null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.patient', to_field='patient_id')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_id', models.CharField(default=core.utils.create_new_ref_number, editable=False, max_length=50, unique=True)),
                ('payment_code', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('totalamount_in_words', models.CharField(max_length=200)),
                ('patient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.patient', to_field='patient_id')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
