# Generated by Django 4.1.3 on 2022-11-09 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_patient_annual_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
