# Generated by Django 4.1.3 on 2022-11-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_patient_signature_patient_medcare_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documents", old_name="payment_id", new_name="doc_id",
        ),
        migrations.RenameField(
            model_name="visits",
            old_name="disbursement_date",
            new_name="admission_date",
        ),
        migrations.AddField(
            model_name="visits",
            name="diagnosis",
            field=models.TextField(default="No Diagnosis"),
        ),
        migrations.AddField(
            model_name="visits",
            name="release_date",
            field=models.DateField(default="2020-01-01", null=True),
        ),
    ]
