# Generated by Django 4.1.3 on 2022-11-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_payment_id_documents_doc_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documents", old_name="patient_account", new_name="patient",
        ),
    ]
