# Generated by Django 4.1.3 on 2022-11-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_patient_account_documents_patient"),
    ]

    operations = [
        migrations.RemoveField(model_name="documents", name="amount",),
        migrations.RemoveField(model_name="documents", name="payment_code",),
        migrations.RemoveField(model_name="documents", name="total_amount",),
        migrations.RemoveField(model_name="documents", name="totalamount_in_words",),
        migrations.AddField(
            model_name="documents",
            name="upload",
            field=models.FileField(default="null", upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
