# Generated by Django 4.1.3 on 2022-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_documents_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visits",
            name="visit_status",
            field=models.CharField(
                choices=[
                    ("Served", "Served"),
                    ("Inservice", "Inservice"),
                    ("Waiting", "Waiting"),
                ],
                default="UnAssigned",
                max_length=50,
                null=True,
            ),
        ),
    ]
