# Generated by Django 4.1.3 on 2022-11-11 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_patient_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="assigned_to",),
        migrations.AddField(
            model_name="visits",
            name="assigned_to",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
