# Generated by Django 4.1.3 on 2022-11-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_report_visit_report_blood_type_report_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
