# Generated by Django 4.1.3 on 2022-11-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_report_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report", name="medcare", field=models.CharField(max_length=50),
        ),
    ]
